# Settings for processing steps
# =============================

# MS cycle timings
# ----------------
blank_cycles: 58
signal_cycles:
  - 60
  - 172


# package settings
# ----------------
sample_map: "inputs/sample_map.csv"
# data files settings
data_dir: "inputs/data/" # where the data files are
output_dir: "output/" # where to save CSV files and plots
file_ext: ".exp" # the file extension of the data files
header_row: 22 # the row containing column headers (top row is row 0)
comment_char: "*" # ignore any row starting with this (one character only)
index_col: "Cycle" # which column to reference rows as
intensity_cols: # the column names holding intensity (voltage) data
  - 202Hg
  - 204Pb
  - 206Pb
  - 207Pb
  - 208Pb