# Settings for processing steps
# =============================

# MS cycle timings
# ----------------
blank_cycles: 56
signal_cycles:
  - 60
  - 114


# package settings
# ----------------
sample_map: "inputs/run1/sample-map.csv"
# data files settings
data_dir: "inputs/run1/data/" # where the data files are
output_dir: "output/run1/" # where to save CSV files and plots
file_ext: ".exp" # the file extension of the data files
header_row: 22 # the row containing column headers (top row is row 0)
comment_char: "*" # ignore any row starting with this (one character only)
index_col: "Cycle" # which column to reference rows as
intensity_cols: # the column names holding intensity (voltage) data
  - 202Hg
  - 204Pb
  - 206Pb
  - 207Pb
  - 208Pb
low_signal_metric: "208Pb" # column name from the raw files of one isotope (e.g. "208Pb")
low_signal_level: 0.005
low_cycles_warning_frac: 0.5 # percentage of cycles left after cleaning below which to warn
blank_upper_limit: 0.001
